version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: taw-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: taw_airline
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - taw-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taw-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/taw_airline?authSource=admin
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - taw-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taw-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: development
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - taw-network

volumes:
  mongodb_data:

networks:
  taw-network:
    driver: bridge